name: Video Factory Run
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Multimedia Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install requests g4f edge-tts moviepy==1.0.3 imageio==2.25.1
      - name: Execute Factory Script
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: python main.py
      - name: Save Video File
        uses: actions/upload-artifact@v3
        with:
          name: Final-Military-Movie
          path: final_mission_video.mp4
